config/routes.rb
Rails.application.routes.draw do
  resources :flats
  # resources :remarks
  resources :posts do
    resources :remarks
  end
  get "about", to: "about#index"
  # resources :likes
  put '/post/:id/like', to: 'posts#like', as: 'like'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # resources :articles, only: %i[new create index show]
  resources :categories do
    resources :articles do
      resources :comments
    end
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :destroy
  has_many_attached :photos
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
    @category = Category.find(params[:category_id])
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @category = Category.find(params[:category_id])
    @article.user_id = current_user.id
    @article.category_id = @category.id
    if @article.save
      redirect_to category_path(@category)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @category = Category.find(params[:category_id])
    if params[:query].present?
      sql_query = <<~SQL
        articles.content ILKE :query
        OR articles.summary ILIKE :query
        OR articles.title ILIKE :query
        OR category.title ILIKE :query
        OR category.content ILIKE :query
      SQL
      @articles = Article.joins(:category).where(sql_query, query: "%#{ params[:query]}%")
    else
      @articles = Article.all
    end
  end

  def edit
    @category = Category.find(params[:category_id])
    @article = Article.find(params[:id])
  end

  def update
    @category = Category.find(params[:category_id])
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to category_path(@category)
  end

  def destroy
    @article = Article.find(params[:id])
    @category = Category.find(params[:category_id])
    @article.destroy
    redirect_to category_path(@category)
  end

  def show
    @article = Article.find(params[:id])
    @comments = Comment.where(article_id: @article)
  end

  private

  def article_params
    params.require(:article).permit(:title, :meta_title, :summary, :content, :slug, photos: [])
  end
end

app/views/articles/_form.html.erb
 <%= simple_form_for([@category, @article]) do |f| %>
    <%= f.input :title %>
    <%= f.input :meta_title %>
    <%= f.input :photo, as: :file %>
    <%= f.input :summary %>
    <%= f.input :content %>
    <%= f.input :slug %>
    <%= f.input :location, input_html: {data: {address_autocomplete_target: "address"}}, class: "d-none",
  wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}} %>
    <%= f.submit "Add Article" %>
  <% end %>

app/views/articles/_info_window.html.erb
<h2><%= article.title %></h2>
<p><%= article.location %></p>

app/views/articles/edit.html.erb
<p>edit article page</p>
 <%= simple_form_for([@category, @article]) do |f| %>
    <%= f.input :title %>
    <%= f.input :meta_title %>
    <%= f.input :summary %>
    <%= f.input :content %>
    <%= f.input :slug %>
    <%= f.submit "Update Article" %>
  <% end %>

app/views/articles/index.html.erb
<p>articles index</p>
<%= form_with url: category_articles_path(@category), method: :get, class: "d-flex" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find an article"
  %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>

<% @articles.each do |article| %>
  <%= article.title %> |
  <%= article.summary %>  |
<% end %>
<%= link_to "home page", root_path %>
<div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
<div id='map' style='width: 400px; height: 300px;'></div>

app/views/articles/new.html.erb
<p>articles new page</p>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<p>article show page</p>
<% @article.photos.each do |photo| %>
  <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
<% end %><%= @article.title %> |
<%= @article.meta_title %> |
<%= @article.summary %>  |
<%= @article.content %>  |
<%= @article.slug %>  |
<%= @article.user_id %>
<%= link_to "new comment", new_category_article_comment_path(@article.category_id, @article) %>
<% @comments.each do |comment| %>
  <%= comment.title %>
  <%= comment.content %>
  <%= link_to "edit this comment", edit_category_article_comment_path(@article.category_id, @article, comment) %>
  <%= link_to "show this specific comment", category_article_comment_path(@article.category_id, @article, comment) %>
  <%= link_to "destroy this comment", category_article_comment_path(@article.category_id, @article, comment), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
  <%# <%= link_to "edit this comment", edit_article_comment_path(comment) %> %>
<% end %>

<%# <%= link_to "edit", edit_article_path(article) %>
<%# <%= link_to "destroy", article_path(article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
<%# <%= link_to "show comments", article_comments_path(@article) %> %>
<%= link_to  "back to category show", category_path(@article.category_id) %>
<div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>