config/routes.rb
Rails.application.routes.draw do
  resources :flats
  # resources :remarks
  resources :posts do
    resources :remarks
  end
  get "about", to: "about#index"
  # resources :likes
  put '/post/:id/like', to: 'posts#like', as: 'like'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # resources :articles, only: %i[new create index show]
  resources :categories do
    resources :articles do
      resources :comments
    end
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :remarks, dependent: :destroy
  has_one_attached :photo
  validates :photo, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[edit update destroy create new show index]

  def like
    @post = Post.all.find(params[:id])
    Like.create(user_id: current_user.id, post_id: @post.id)
    redirect_to post_path(@post)
  end
  # GET /posts or /posts.json
  def index
    @posts = policy_scope(Post)
    @posts = Post.all
    @markers = @posts.geocoded.map do |post|
      {
        lat: post.latitude,
        lng: post.longitude,
        info_window: render_to_string(partial: "info_window", locals: {post: post}),
        image_url: helpers.asset_url("https://res.cloudinary.com/dfipoufmj/image/upload/v1666713742/rory_zoeandcam_a29pkj.jpg")
      }
    end

    if params[:query].present?
      sql_query = <<~SQL
        posts.title ILIKE :query
        OR users.first_name ILIKE :query
        OR users.last_name ILIKE :query
      SQL
      @posts = Post.joins(:user).where(sql_query, query: "%#{params[:query]}%")
    else
      @posts = Post.all
    end
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
    @remarks = Remark.where(post_id: @post)
    authorize @post
  end

  # GET /posts/new
  def new
    @post = Post.new
    authorize @post
  end

  # GET /posts/1/edit
  def edit
    authorize @post
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    authorize @post
    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    authorize @post
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    authorize @post

    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :address, :content, :user_id, :photo)
    end
end

app/views/posts/_form.html.erb
  <div class="form-inputs">
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <%= f.input :title %>
    <%= f.input :address,
      input_html: {data: {address_autocomplete_target: "address"}},
      wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}} %>
    <%= f.input :content %>
    <%= f.input :category, collection: ["Outdoor", "Hospitality", "Finance", "The Arts", "Business", "Trade", "Traditional"] %>
    <%= f.input :photo, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/_info_window.html.erb
<h2><%= post.title %></h2>
<p><%= post.address %></p>
<%# <div class="btn-ghost"> %>
  <%= link_to "View", post_path(post), class: "btn btn-ghost" %>
<%# </div> %>
<%# <button href="post_path" class="btn-ghost">Show</button> %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= post.address %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= post.content %>
  </p>

  <p>
    <strong>User:</strong>
    <%= post.user_id %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1 class="form-header">Edit post</h1>

<%= render "form", post: @post %>

<br>

<div class="form-header">
  <%= link_to "Show this post", @post, class: "btn-ghost" %>
  <%= link_to "Back to posts", posts_path, class: "btn-ghost" %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="index-page-content">
  <div class="index-posts-container">
    <div class="index-posts-grid">
      <% @posts.each do |post| %>
        <%= link_to post do %>
          <div class="index-post-card">
            <%= cl_image_tag post.photo.key %>
            <div class="index-post-card-text">
              <h2><%= post.title %></h2>
              <p><%= post.created_at.to_date %></p>
              <p><%= post.content %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div style="width: 100%; height: 600px;", class="map",
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/posts/new.html.erb
<h1 class="form-header">New post</h1>

<%= render "form", post: @post %>

<br>

<div class="form-header">
  <%= link_to "Back to posts", posts_path, class: "btn-ghost" %>
</div>

app/views/posts/show.html.erb
<div class="page-content">
  <h1 id="post-show-title"><%= @post.title %></h1>
  <%= cl_image_tag @post.photo.key, id: "blog-show-photo" %>
  <div class="post-show-content-block">
    <div class="post-data">
      <h2>Posted - <%= @post.created_at.to_date %></h2>
      <%# <h3><%= @post.created_at.to_date %></h3>
    </div>
    <div class="edit-post-button">
      <% if policy(@post).edit? %>
        <%= link_to "Edit Post", edit_post_path(@post), class: "btn-ghost" %>
      <% end %>
  </div>
    <p id="post-content"><%= @post.content %></p>
    <div class="remarks-container">
      <div class="post-comment">
        <%= link_to "Comment on this post", new_post_remark_path(@post), class: "btn-ghost" %>
      </div>
      <% @remarks.each do |remark| %>
        <p><%= remark.title %></p>
        <p><%= remark.content %></p>
        <div class="comment-buttons">
          <%= link_to "Edit", edit_post_remark_path(@post, remark), class: "btn-ghost" if (current_user.id == remark.user_id) || (current_user.admin?) %>
          <%= link_to "Delete", post_remark_path(@post, remark), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn-ghost" if (current_user.id == remark.user_id) || (current_user.admin?) %>
        </div>
      <% end %>
    </div>
  </div>
</div>