config/routes.rb
Rails.application.routes.draw do
  resources :flats
  # resources :remarks
  resources :posts do
    resources :remarks
  end
  get "about", to: "about#index"
  # resources :likes
  put '/post/:id/like', to: 'posts#like', as: 'like'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # resources :articles, only: %i[new create index show]
  resources :categories do
    resources :articles do
      resources :comments
    end
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles, dependent: :destroy
  has_one_attached :photo
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @categories = Category.all
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    redirect_to categories_path
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  def show
    @category = Category.find(params[:id])
    @articles = Article.where(category_id: @category)
  end

  private

  def category_params
    params.require(:category).permit(:title, :meta_title, :content, :slug, :photo)
  end
end

app/views/categories/_form.html.erb
 <%= simple_form_for (@category) do |f| %>
    <%= f.input :title %>
    <%= f.input :meta_title %>
    <%= f.input :content %>
    <%= f.input :slug %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Add category" %>
  <% end %>

app/views/categories/edit.html.erb
<p>category edit page</p>
 <%= simple_form_for (@category) do |f| %>
    <%= f.input :title %>
    <%= f.input :meta_title %>
    <%= f.input :content %>
    <%= f.input :slug %>
    <%= f.submit "Add category" %>
  <% end %>

app/views/categories/index.html.erb
 <p>category index</p>
 <%= link_to "new category", new_category_path %>
<% @categories.each do |category| %>
  <%= cl_image_tag category.photo.key, height: 300, width: 400, crop: :fill %>
  <%= category.title %>
  <%= category.content %>
  <%= link_to "show", category_path(category) %>
  <%= link_to "edit this category", edit_category_path(category) %>
  <%= link_to "delete this category", category_path(category), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
<% end %>

app/views/categories/new.html.erb
<p>category new page</p>
 <%= simple_form_for (@category) do |f| %>
    <%= f.input :title %>
    <%= f.input :meta_title %>
    <%= f.input :content %>
    <%= f.input :slug %>
    <%= f.submit "Add category" %>
  <% end %>

app/views/categories/show.html.erb
<p>category show page</p>
<%= cl_image_tag @category.photo.key, height: 300, width: 400, crop: :fill %>
<%= @category.title %>
<%= @category.content %>
<%= link_to "create a new article", new_category_article_path(@category) %>
<% @articles.each do |article| %>
  <%= article.title %>
  <%= link_to "show", category_article_path(@category, article) %>
  <%= link_to "destroy", category_article_path(@category, article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
  <%= link_to "edit", edit_category_article_path(@category, article) %>
<% end %>
<%= link_to "home", root_path %>