config/routes.rb
Rails.application.routes.draw do
  resources :flats
  # resources :remarks
  resources :posts do
    resources :remarks
  end
  get "about", to: "about#index"
  # resources :likes
  put '/post/:id/like', to: 'posts#like', as: 'like'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # resources :articles, only: %i[new create index show]
  resources :categories do
    resources :articles do
      resources :comments
    end
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/remark.rb
class Remark < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/remarks_controller.rb
class RemarksController < ApplicationController
  before_action :set_remark, only: %i[ show edit update destroy ]

  # GET /remarks or /remarks.json
  def index
    authorize @remark
    @remarks = Remark.all
    @post = Post.find(params[:post_id])
  end

  # GET /remarks/1 or /remarks/1.json
  def show
  end

  # GET /remarks/new
  def new
    @remark = Remark.new
    @post = Post.find(params[:post_id])
    authorize @remark
  end

  # GET /remarks/1/edit
  def edit
    authorize @remark
    @remark = Remark.find(params[:id])
    @post = Post.find(params[:post_id])
  end

  # POST /remarks or /remarks.json
  def create
    @remark = Remark.new(remark_params)
    @post = Post.find(params[:post_id])
    @remark.user_id = current_user.id
    @remark.post_id = @post.id
    respond_to do |format|
      if @remark.save
        format.html { redirect_to post_path(@post), notice: "Remark was successfully created." }
        format.json { render :show, status: :created, location: @remark }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @remark.errors, status: :unprocessable_entity }
      end
    end
    authorize @remark
  end

  # PATCH/PUT /remarks/1 or /remarks/1.json
  def update
    authorize @remark
    @post = Post.find(params[:post_id])
    @remark.user_id = current_user
    respond_to do |format|
      if @remark.update(remark_params)
        format.html { redirect_to post_path(@post), notice: "Remark was successfully updated." }
        format.json { render :show, status: :ok, location: @remark }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @remark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /remarks/1 or /remarks/1.json
  def destroy
    authorize @remark
    @post = Post.find(params[:post_id])
    @remark.destroy
    respond_to do |format|
      format.html { redirect_to post_path(@post), notice: "Remark was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_remark
      @remark = Remark.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def remark_params
      params.require(:remark).permit(:title, :content, :user_id, :post_id)
    end
end

app/views/remarks/_form.html.erb
<%= simple_form_for([@post, @remark]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Submit" %>
  </div>
<% end %>

app/views/remarks/_remark.html.erb
<div id="<%= dom_id remark %>">
  <p>
    <strong>Title:</strong>
    <%= remark.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= remark.content %>
  </p>

  <p>
    <strong>User:</strong>
    <%= remark.user_id %>
  </p>

  <p>
    <strong>Post:</strong>
    <%= remark.post_id %>
  </p>

</div>

app/views/remarks/edit.html.erb
<h1 class="form-header">Edit your comment</h1>

<%= render "form", remark: @remark %>

<div>
  <%= link_to "Back to post show page", post_path(@post) %>
</div>

app/views/remarks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Remarks</h1>

<div id="remarks">
  <% @remarks.each do |remark| %>
    <%= render remark %>
    <p>
      <%= link_to "Show this remark", post_remark_path(remark) %>
    </p>
  <% end %>
</div>

<%= link_to "New remark", new_remark_path %>

app/views/remarks/new.html.erb
<h1 class="form-header">New comment</h1>

<%= render "form", remark: @remark %>

<div class="form-header">
  <%= link_to "Back to the post", post_path(@post), class: "btn-ghost", id: "new-comment-back-btn"%>
</div>

app/views/remarks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @remark %>

<div>
  <%= link_to "Edit this remark", edit_post_remark_path(@remark) %> |
  <%= link_to "Back to remarks", remarks_path %>

  <%= button_to "Destroy this remark", @remark, method: :delete %>
</div>